### ISSUE TITLE
please make a invitable bot link

### ISSUE THREAD

**Issue by ranehal** [nano-shino/genshinhelper#9]
please make a invitable bot link

**Comment by EffortlessFury** [comment]
I'm pretty sure the creator does not host an instance of the bot to be used by everyone. You're meant to run the code and the bot yourself.

**Comment by nano-shino** [comment]
@EffortlessFury was correct. There's no bot invite link because that wasn't the objective of this repo. If you want a public bot, check out the many bots that are in the genshin.py server https://discord.gg/sMkSKRPuCR. Many people have made their own bots with different flavors. The goal of this project is to make a self-hosting bot with your own flavor.
Now if you just want to test out this repo before hosting yourself, feel free to join my support server which has a limited version of the bot. It's in the readme doc.
